version: "3.8"
services:
  postgres:
    restart: always
    image: postgres:14.3-alpine
    container_name: base_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  nextjs:
    restart: always
    container_name: base_nextjs
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./:/app/frontend/
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - postgres

